export type ValidSkills =
  | "Next.js"
  | "Executive Support"
  | "Microsoft Excel"
  | "Administration"
  | "Content Creation"
  | "Social Media Strategy"
  | "Zustand"
  | "Photography"
  | "Professional Communication"
  | "Network Administration"
  | "Database Design"
  | "Server Management"
  | "Troubleshooting"
  | "WAN/LAN"
  | "Project Management"
  | "Digital Documentation"
  | "Video Editing"
  | "Time Management"
  | "React.js (Vite)"
  | "Tesseract.js / OCR API"
  | "Cloudinary"
  | "Express"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "RajaOngkir API"
  | "Material UI"
  | "Midtrans API"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion";

export type ValidCategory =
  | "Full Stack"
  | "Real-time Systems"
  | "Social Networking"
  | "Fintech"
  | "Artificial Intelligence"
  | "SaaS"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Geo-Spatial"
  | "3D Modeling"
  | "Fintech Integration";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume";
